on:
  workflow_dispatch:
  schedule:
    - cron: "30 12 * * MON"
  push:

name: Scala Steward
permissions:
  contents: write
  pull-requests: write

jobs:
  scala-steward:
    runs-on: ubuntu-22.04
    name: Scala Steward
    steps:
      - name: Scala Steward
        uses: scala-steward-org/scala-steward-action@v2
        with:
          scala-steward-version: 0.30.2